#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
norm="$(printf '\033[0m')" #returns to "normal"
stage="$(printf '\033[0;4;34m')" # blink
info="$(printf '\033[0;36m')" # cyan
warning="$(printf '\033[0;35m')" # underlined light yellow
crit="$(printf '\033[0;4;35m')" # blink light yellow
error="$(printf '\033[0;1;31m')" # bold light red

$DIR/vivado-wrapper $@ | sed -u -e "s/INFO/${info}&${norm}/g"\
| sed -u -e "s/CRITICAL WARNING/${cirt}&${norm}/g"\
| sed -u -e "s/WARNING/${warning}&${norm}/g"\
| sed -u -e "s/ERROR/${error}&${norm}/g"\
| sed -u -e "s/Scanning sources/${stage}&${norm}/g"\
| sed -u -e "s/Creating bitstream/${stage}&${norm}/g"\
| sed -u -e "s/Generating Base Project/${stage}&${norm}/g"\
| sed -u -e "s/Converting VWC Constraints to XDC/${stage}&${norm}/g"\
| sed -u -e "s/Initializing Project/${stage}&${norm}/g" \
| sed -u -e "s/Loading data files/${stage}&${norm}/g" \
| sed -u -e "s/Loading site data/${stage}&${norm}/g" \
| sed -u -e "s/Loading route data/${stage}&${norm}/g" \
| sed -u -e "s/Processing options/${stage}&${norm}/g" \
| sed -u -e "s/Creating bitmap/${stage}&${norm}/g" \
| sed -u -e "s/Writing bitstream/${stage}&${norm}/g" \
| sed -u -e "s/Bitgen Completed Successfully/${stage}&${norm}/g" \
| sed -u -e "s/Starting Routing Task/${stage}&${norm}/g" \
| sed -u -e "s/Running DRC/${stage}&${norm}/g" \
| sed -u -e "s/Phase [0-9][0-9]*\(\.[0-9]\)* .*/${stage}&${norm}/g"

